analytics:
  google:
    id: UA-100531691-1
  piwik:
    id: 1
    api:
      url: https://vps.irockbunny.com/analytics/?callback=?
      token: d02aaf812df43e020db5de7f5b0f15a8

repository: NavAwesome/navawesome.github.io
repository_url: https://github.com/NavAwesome/navawesome.github.io

timezone: Asia/Shanghai

name: 导航 · NavAwesome
author: NavAwesome
author_url: https://navawesome.github.io/
description: A Navigation Website for BYR
keywords: 导航, NavAwesome, Navi, Navigation
url: https://navawesome.github.io/
contact: contact[at]irockbunny[dot]com

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor